# <center>Clustering of titles</center>
---

This code aims to cluster the titles of YouTube videos, trying to search for videos related to politics

In [3]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk

nltk.download("stopwords")
stop_words = stopwords.words("english") + stopwords.words("portuguese") + stopwords.words("french")

[nltk_data] Downloading package stopwords to /home/ester/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
df = pd.read_csv("../data/youtube_titles_2.csv")
display(df)

,video_id,title,youtube_video_link
0,oGev0AdOaxg,"La revue de presse du mardi 14 novembre, avec ...",https://www.youtube.com/watch?v=oGev0AdOaxg
1,BFQ8gqvkjz8,nasthug | Boiler Room Tokyo: Tohji Presents u-ha,https://www.youtube.com/watch?v=BFQ8gqvkjz8
2,X928ajAsdMM,Puddle Of Mudd - Livin' On Borrowed Time (Offi...,https://www.youtube.com/watch?v=X928ajAsdMM
3,thblw2XHUpw,Platonismo e Virtudes,https://www.youtube.com/watch?v=thblw2XHUpw
4,PWbMXDvviTw,The Titans: Rise of the Unstoppable,https://www.youtube.com/watch?v=PWbMXDvviTw
...,...,...,...
429849,6qO4TxA7U3c,Putin's Missiles 'Hit' NATO Nation's Train Car...,https://www.youtube.com/watch?v=6qO4TxA7U3c
429850,ojLpPQiFguE,"Stop the ""Moonlighting"" Bill. Tharman to Resig...",https://www.youtube.com/watch?v=ojLpPQiFguE
429851,rNBc4XdkfPA,I'm In Public Ma'am!!,https://www.youtube.com/watch?v=rNBc4XdkfPA
429852,bM2P5eAFyGU,LUCIFER (Zwischen Licht und Finsternis),https://www.youtube.com/watch?v=bM2P5eAFyGU
429853,5yxaRL2G8TU,Юридический бизнес-форум: лидеры и новая реаль...,https://www.youtube.com/watch?v=5yxaRL2G8TU

In [5]:
def pre_processing(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-ZÀ-ÿ\s]", "", text)
    return text.strip()

df["clean_title"] = df["title"].apply(pre_processing)
display(df)

,video_id,title,youtube_video_link,clean_title
0,oGev0AdOaxg,"La revue de presse du mardi 14 novembre, avec ...",https://www.youtube.com/watch?v=oGev0AdOaxg,la revue de presse du mardi novembre avec ale...
1,BFQ8gqvkjz8,nasthug | Boiler Room Tokyo: Tohji Presents u-ha,https://www.youtube.com/watch?v=BFQ8gqvkjz8,nasthug boiler room tokyo tohji presents uha
2,X928ajAsdMM,Puddle Of Mudd - Livin' On Borrowed Time (Offi...,https://www.youtube.com/watch?v=X928ajAsdMM,puddle of mudd livin on borrowed time officia...
3,thblw2XHUpw,Platonismo e Virtudes,https://www.youtube.com/watch?v=thblw2XHUpw,platonismo e virtudes
4,PWbMXDvviTw,The Titans: Rise of the Unstoppable,https://www.youtube.com/watch?v=PWbMXDvviTw,the titans rise of the unstoppable
...,...,...,...,...
429849,6qO4TxA7U3c,Putin's Missiles 'Hit' NATO Nation's Train Car...,https://www.youtube.com/watch?v=6qO4TxA7U3c,putins missiles hit nato nations train carryin...
429850,ojLpPQiFguE,"Stop the ""Moonlighting"" Bill. Tharman to Resig...",https://www.youtube.com/watch?v=ojLpPQiFguE,stop the moonlighting bill tharman to resign f...
429851,rNBc4XdkfPA,I'm In Public Ma'am!!,https://www.youtube.com/watch?v=rNBc4XdkfPA,im in public maam
429852,bM2P5eAFyGU,LUCIFER (Zwischen Licht und Finsternis),https://www.youtube.com/watch?v=bM2P5eAFyGU,lucifer zwischen licht und finsternis
429853,5yxaRL2G8TU,Юридический бизнес-форум: лидеры и новая реаль...,https://www.youtube.com/watch?v=5yxaRL2G8TU,