In [1]:
import pandas as pd

df_results = pd.read_csv("bertopic_parameter_tuning_results_sample_3.csv")
data_frame = pd.read_csv("preprocessed_english_titles.csv",engine = 'python', on_bad_lines='skip')

In [2]:
# Calcula a média das métricas
df_results['mean_score'] = df_results[['coherence', 'diversity', 'silhouette']].mean(axis=1)

# 20 melhores por média
top20_mean = df_results.sort_values(by='mean_score', ascending=False).head(20)

# 20 melhores por diversidade, mas ordenados pela média
top20_diversity = (
    df_results.sort_values(by='diversity', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

# 20 melhores por coerência, mas ordenados pela média
top20_coherence = (
    df_results.sort_values(by='coherence', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

# 20 melhores por silhueta, mas ordenados pela média
top20_silhouette = (
    df_results.sort_values(by='silhouette', ascending=False)
    .head(20)
    .sort_values(by='mean_score', ascending=False)
)

best_mean_row = top20_mean
best_coherence_row = top20_coherence
best_silhouette_row = top20_silhouette
best_diversity_row = top20_diversity
# Exibe os resultados
display(best_mean_row)
display(best_coherence_row)
display(best_diversity_row)
display(best_silhouette_row)

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score
572,20,10,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.746033,0.993750,0.850889,0.863558
575,20,10,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.746033,0.993750,0.850889,0.863558
302,10,10,0.5,100,100,0.1,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
305,10,10,0.5,100,100,0.5,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
287,10,10,0.5,50,100,0.5,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
284,10,10,0.5,50,100,0.1,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
413,20,5,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.716017,0.993750,0.821830,0.843866
410,20,5,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.716017,0.993750,0.821830,0.843866
554,20,10,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.689743,0.995000,0.846561,0.843768
557,20,10,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.689743,0.995000,0.846561,0.843768
269,10,10,0.1,150,100,0.5,paraphrase-MiniLM-L6-v2,0.671996,0.983333,0.829509,0.828279
266,10,10,0.1,150,100,0.1,paraphrase-MiniLM-L6-v2,0.671996,0.983333,0.829509,0.828279
248,10,10,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.666963,0.990000,0.822134,0.826366
251,10,10,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.666963,0.990000,0.822134,0.826366
230,10,10,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.638722,0.991667,0.837396,0.822595
233,10,10,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.638722,0.991667,0.837396,0.822595
194,10,10,0.0,100,100,0.1,paraphrase-MiniLM-L6-v2,0.634840,0.995833,0.824174,0.818282
197,10,10,0.0,100,100,0.5,paraphrase-MiniLM-L6-v2,0.634840,0.995833,0.824174,0.818282
395,20,5,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.682199,0.995455,0.774016,0.817223
392,20,5,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.682199,0.995455,0.774016,0.817223

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score
575,20,10,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.746033,0.993750,0.850889,0.863558
572,20,10,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.746033,0.993750,0.850889,0.863558
284,10,10,0.5,50,100,0.1,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
302,10,10,0.5,100,100,0.1,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
305,10,10,0.5,100,100,0.5,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
287,10,10,0.5,50,100,0.5,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
413,20,5,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.716017,0.993750,0.821830,0.843866
410,20,5,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.716017,0.993750,0.821830,0.843866
557,20,10,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.689743,0.995000,0.846561,0.843768
554,20,10,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.689743,0.995000,0.846561,0.843768
395,20,5,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.682199,0.995455,0.774016,0.817223
392,20,5,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.682199,0.995455,0.774016,0.817223
107,10,5,0.1,150,100,0.5,paraphrase-MiniLM-L6-v2,0.683231,0.983333,0.752275,0.806280
104,10,5,0.1,150,100,0.1,paraphrase-MiniLM-L6-v2,0.683231,0.983333,0.752275,0.806280
446,20,5,0.5,50,100,0.1,paraphrase-MiniLM-L6-v2,0.693459,0.987500,0.695206,0.792055
449,20,5,0.5,50,100,0.5,paraphrase-MiniLM-L6-v2,0.693459,0.987500,0.695206,0.792055
608,20,10,0.5,50,100,0.1,paraphrase-MiniLM-L6-v2,0.697319,0.975000,0.609449,0.760589
611,20,10,0.5,50,100,0.5,paraphrase-MiniLM-L6-v2,0.697319,0.975000,0.609449,0.760589
221,10,10,0.1,50,5,0.5,paraphrase-MiniLM-L6-v2,0.680003,0.975000,0.256851,0.637285
239,10,10,0.1,100,5,0.5,paraphrase-MiniLM-L6-v2,0.680003,0.975000,0.256851,0.637285

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score
596,20,10,0.5,50,5,0.1,paraphrase-MiniLM-L6-v2,0.576537,1.0,0.586878,0.721138
31,10,5,0.0,100,100,0.1,all-distilroberta-v1,0.668390,1.0,0.333316,0.667235
16,10,5,0.0,50,100,0.5,all-distilroberta-v1,0.668390,1.0,0.333316,0.667235
52,10,5,0.0,150,100,0.5,all-distilroberta-v1,0.668390,1.0,0.333316,0.667235
49,10,5,0.0,150,100,0.1,all-distilroberta-v1,0.668390,1.0,0.333316,0.667235
34,10,5,0.0,100,100,0.5,all-distilroberta-v1,0.668390,1.0,0.333316,0.667235
22,10,5,0.0,100,5,0.5,all-distilroberta-v1,0.636131,1.0,0.331857,0.655996
19,10,5,0.0,100,5,0.1,all-distilroberta-v1,0.636131,1.0,0.331857,0.655996
37,10,5,0.0,150,5,0.1,all-distilroberta-v1,0.636131,1.0,0.331857,0.655996
614,20,10,0.5,100,5,0.1,paraphrase-MiniLM-L6-v2,0.529714,1.0,0.408848,0.646187
583,20,10,0.1,150,10,0.1,all-distilroberta-v1,0.622899,1.0,0.280184,0.634361
586,20,10,0.1,150,10,0.5,all-distilroberta-v1,0.622899,1.0,0.280184,0.634361
592,20,10,0.1,150,100,0.5,all-distilroberta-v1,0.615807,1.0,0.286446,0.634084
589,20,10,0.1,150,100,0.1,all-distilroberta-v1,0.615807,1.0,0.286446,0.634084
617,20,10,0.5,100,5,0.5,paraphrase-MiniLM-L6-v2,0.555761,1.0,0.308115,0.621292
599,20,10,0.5,50,5,0.5,paraphrase-MiniLM-L6-v2,0.561534,1.0,0.296033,0.619189
613,20,10,0.5,100,5,0.1,all-distilroberta-v1,0.660686,1.0,0.094619,0.585102
616,20,10,0.5,100,5,0.5,all-distilroberta-v1,0.660686,1.0,0.094619,0.585102
615,20,10,0.5,100,5,0.5,all-MiniLM-L6-v2,0.462490,1.0,0.250984,0.571158
58,10,5,0.1,50,5,0.5,all-distilroberta-v1,0.512220,1.0,-0.327241,0.394993

,n_neighbors,n_components,min_dist,min_cluster_size,min_samples,cluster_eps,embedding_model,coherence,diversity,silhouette,mean_score
575,20,10,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.746033,0.993750,0.850889,0.863558
572,20,10,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.746033,0.993750,0.850889,0.863558
287,10,10,0.5,50,100,0.5,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
305,10,10,0.5,100,100,0.5,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
284,10,10,0.5,50,100,0.1,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
302,10,10,0.5,100,100,0.1,paraphrase-MiniLM-L6-v2,0.742109,0.981250,0.853484,0.858948
413,20,5,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.716017,0.993750,0.821830,0.843866
410,20,5,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.716017,0.993750,0.821830,0.843866
557,20,10,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.689743,0.995000,0.846561,0.843768
554,20,10,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.689743,0.995000,0.846561,0.843768
266,10,10,0.1,150,100,0.1,paraphrase-MiniLM-L6-v2,0.671996,0.983333,0.829509,0.828279
269,10,10,0.1,150,100,0.5,paraphrase-MiniLM-L6-v2,0.671996,0.983333,0.829509,0.828279
251,10,10,0.1,100,100,0.5,paraphrase-MiniLM-L6-v2,0.666963,0.990000,0.822134,0.826366
248,10,10,0.1,100,100,0.1,paraphrase-MiniLM-L6-v2,0.666963,0.990000,0.822134,0.826366
230,10,10,0.1,50,100,0.1,paraphrase-MiniLM-L6-v2,0.638722,0.991667,0.837396,0.822595
233,10,10,0.1,50,100,0.5,paraphrase-MiniLM-L6-v2,0.638722,0.991667,0.837396,0.822595
197,10,10,0.0,100,100,0.5,paraphrase-MiniLM-L6-v2,0.634840,0.995833,0.824174,0.818282
194,10,10,0.0,100,100,0.1,paraphrase-MiniLM-L6-v2,0.634840,0.995833,0.824174,0.818282
179,10,10,0.0,50,100,0.5,paraphrase-MiniLM-L6-v2,0.617116,0.996154,0.805178,0.806149
176,10,10,0.0,50,100,0.1,paraphrase-MiniLM-L6-v2,0.617116,0.996154,0.805178,0.806149

In [3]:
'''Remoção de Stopwords'''
from PreProcessing.pre_processing import PreProcessing
from nltk.corpus import stopwords

pp = PreProcessing(language="en")

custom_stopwords = [line.strip() for line in open('stopwords.txt', 'r', encoding='utf-8')]
english_stopwords = set(stopwords.words('english'))
pp.append_stopwords_list(list(english_stopwords - set(pp.stopwords)) + custom_stopwords)

data_frame["clean_text"] = data_frame["clean_text"].apply(
    lambda t: " ".join(
        [w for w in pp.remove_stopwords(t).split() if len(w) <= 20]
    )
)

In [11]:
import csv

nan_count = data_frame['clean_text'].isna().sum()
df = data_frame[data_frame['clean_text'].notna()].reset_index(drop=True)
print(f"{nan_count} rows with NaN in 'clean_text' were removed.")

duplicate_count = df.duplicated(subset=['clean_text']).sum()
df.drop_duplicates(subset=['clean_text'], inplace=True)
print(f"{duplicate_count} duplicate rows based on 'clean_text' were removed.")

print(f"Total documents after cleaning: {len(df)}")

sample_df = df.sample(frac=0.1, random_state=42)
sample_docs = sample_df['clean_text'].tolist()
print(f"Sampled {len(sample_docs)} documents for topic modeling.")

print(len(df))
print(len(sample_df))
df.to_csv("processed_df.csv", index=False, quoting=csv.QUOTE_ALL)
sample_df.to_csv("sample_df.csv", index=False, quoting=csv.QUOTE_ALL)

0 rows with NaN in 'clean_text' were removed.
13039 duplicate rows based on 'clean_text' were removed.
Total documents after cleaning: 673587
Sampled 67359 documents for topic modeling.
673587
67359

In [5]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from meu_bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
from hdbscan import HDBSCAN

default_stopwords = []

def run_bertopic_modeling(docs, n_neighbors, n_components, min_dist, min_cluster_size, min_samples, cluster_eps,embedding_model_name="all-MiniLM-L6-v2"):
    umap_params = {
        "n_neighbors": n_neighbors, 
        "n_components": n_components, 
        "min_dist": min_dist,
        "metric":'cosine',
        "random_state":42
    }

    hdbscan_params = {
        "min_cluster_size": min_cluster_size, 
        "min_samples": min_samples,
        "prediction_data":True,
        "cluster_selection_epsilon": cluster_eps
    }

    bertopic_params = {
        'language': 'english',
        #'verbose': True,
        'top_n_words': 10
    }

    embedding_model = SentenceTransformer(embedding_model_name, device='cuda')
    vectorizer = TfidfVectorizer(stop_words=default_stopwords,ngram_range=(1, 1))

    umap_model = UMAP(**umap_params)
    hdbscan_model = HDBSCAN(**hdbscan_params)

    model = BERTopic(
        **bertopic_params,
        embedding_model=embedding_model,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer,
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True)
    )

    topics, probs = model.fit_transform(docs)
    return model, topics, probs

/home/webmedia2025/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
from IPython.display import display

def show_results(model):

    info = model.get_topic_info()
    display(info)

    topicos = [t for t in model.get_topics().keys() if t != -1]
    fig = model.visualize_barchart(topics=topicos, n_words=10)
    fig.show()

In [7]:
import os

def save_results(model, dir):
    json_path = os.path.join(dir, "topics.json")
    model.save_json(json_path) 

    topicos = [t for t in model.get_topics().keys() if t != -1]
    fig = model.visualize_barchart(topics=topicos, n_words=10)

    barchart_path = os.path.join(dir, "barchart.html")
    fig.write_html(barchart_path) 

    model_path = os.path.join(dir, "bertopic_model")
    model.save(model_path)

    topics_info = model.get_topic_info()
    csv_path = os.path.join(dir, "topics_info.csv")
    topics_info.to_csv(csv_path, index=False)
    
    print(f"Modelo e resultados salvos no diretório '{dir}' (gráfico salvo como HTML)")

In [39]:
for i,row in enumerate(best_mean_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=sample_docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps
    )
    dir = f"best_mean/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=572, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7460334473986139, diversity=0.99375, silhouette=0.850889265537262, mean_score=0.8635575709786253)

2025-10-29 01:07:30,683 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=575, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7460334473986139, diversity=0.99375, silhouette=0.850889265537262, mean_score=0.8635575709786253)

2025-10-29 01:11:20,297 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=302, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 01:15:08,275 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=305, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 01:18:54,962 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=287, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 01:22:37,685 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=284, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 01:26:23,944 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=413, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7160172530564333, diversity=0.99375, silhouette=0.8218297958374023, mean_score=0.843865682964612)

2025-10-29 01:30:05,914 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=410, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7160172530564333, diversity=0.99375, silhouette=0.8218297958374023, mean_score=0.843865682964612)

2025-10-29 01:33:48,088 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=554, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6897430944738395, diversity=0.995, silhouette=0.8465607762336731, mean_score=0.8437679569025042)

2025-10-29 01:37:38,056 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=557, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6897430944738395, diversity=0.995, silhouette=0.8465607762336731, mean_score=0.8437679569025042)

2025-10-29 01:40:37,194 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=269, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6719957762319849, diversity=0.9833333333333332, silhouette=0.8295090198516846, mean_score=0.8282793764723343)

2025-10-29 01:44:04,579 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=266, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6719957762319849, diversity=0.9833333333333332, silhouette=0.8295090198516846, mean_score=0.8282793764723343)

2025-10-29 01:47:33,610 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=248, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6669625134428905, diversity=0.99, silhouette=0.8221344351768494, mean_score=0.8263656495399133)

2025-10-29 01:51:03,091 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=251, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6669625134428905, diversity=0.99, silhouette=0.8221344351768494, mean_score=0.8263656495399133)

2025-10-29 01:54:31,697 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=230, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6387219664036587, diversity=0.9916666666666668, silhouette=0.8373963832855225, mean_score=0.8225950054519493)

2025-10-29 01:58:00,433 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=233, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6387219664036587, diversity=0.9916666666666668, silhouette=0.8373963832855225, mean_score=0.8225950054519493)

2025-10-29 02:01:29,531 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=194, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6348397920549981, diversity=0.9958333333333332, silhouette=0.8241742849349976, mean_score=0.8182824701077763)

2025-10-29 02:04:54,404 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=197, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6348397920549981, diversity=0.9958333333333332, silhouette=0.8241742849349976, mean_score=0.8182824701077763)

2025-10-29 02:08:19,617 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=395, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6821987072562382, diversity=0.9954545454545456, silhouette=0.7740161418914795, mean_score=0.8172231315340878)

2025-10-29 02:12:01,242 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=392, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6821987072562382, diversity=0.9954545454545456, silhouette=0.7740161418914795, mean_score=0.8172231315340878)

2025-10-29 02:15:42,025 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_mean/19' (gráfico salvo como HTML)

In [8]:
for i,row in enumerate(best_coherence_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=sample_docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps
    )
    dir = f"best_coherence/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=575, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7460334473986139, diversity=0.99375, silhouette=0.850889265537262, mean_score=0.8635575709786253)

2025-10-29 11:54:52,017 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=572, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7460334473986139, diversity=0.99375, silhouette=0.850889265537262, mean_score=0.8635575709786253)

2025-10-29 11:57:49,107 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=284, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 12:00:36,747 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=302, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 12:03:16,718 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=305, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 12:05:40,530 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=287, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 12:08:09,368 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=413, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7160172530564333, diversity=0.99375, silhouette=0.8218297958374023, mean_score=0.843865682964612)

2025-10-29 12:10:41,263 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=410, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7160172530564333, diversity=0.99375, silhouette=0.8218297958374023, mean_score=0.843865682964612)

2025-10-29 12:13:07,336 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=557, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6897430944738395, diversity=0.995, silhouette=0.8465607762336731, mean_score=0.8437679569025042)

2025-10-29 12:15:39,705 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=554, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6897430944738395, diversity=0.995, silhouette=0.8465607762336731, mean_score=0.8437679569025042)

2025-10-29 12:18:11,954 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=395, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6821987072562382, diversity=0.9954545454545456, silhouette=0.7740161418914795, mean_score=0.8172231315340878)

2025-10-29 12:20:37,121 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=392, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6821987072562382, diversity=0.9954545454545456, silhouette=0.7740161418914795, mean_score=0.8172231315340878)

2025-10-29 12:23:01,977 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=107, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6832307120221477, diversity=0.9833333333333332, silhouette=0.7522751688957214, mean_score=0.8062797380837341)

2025-10-29 12:25:07,428 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=104, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6832307120221477, diversity=0.9833333333333332, silhouette=0.7522751688957214, mean_score=0.8062797380837341)

2025-10-29 12:27:12,495 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=446, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6934590694085999, diversity=0.9875, silhouette=0.6952062249183655, mean_score=0.7920550981089884)

2025-10-29 12:29:38,233 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=449, n_neighbors=20, n_components=5, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6934590694085999, diversity=0.9875, silhouette=0.6952062249183655, mean_score=0.7920550981089884)

2025-10-29 12:32:04,391 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=608, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6973192850449442, diversity=0.975, silhouette=0.6094487309455872, mean_score=0.7605893386635104)

2025-10-29 12:34:40,765 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=611, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6973192850449442, diversity=0.975, silhouette=0.6094487309455872, mean_score=0.7605893386635104)

2025-10-29 12:37:16,711 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=221, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=5, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6800028499730983, diversity=0.975, silhouette=0.256850928068161, mean_score=0.6372845926804197)

2025-10-29 12:39:27,028 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=239, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=5, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6800028499730983, diversity=0.975, silhouette=0.256850928068161, mean_score=0.6372845926804197)

2025-10-29 12:41:36,974 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_coherence/19' (gráfico salvo como HTML)

In [9]:
for i,row in enumerate(best_diversity_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=sample_docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps
    )
    dir = f"best_diversity/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=596, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=5, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.5765369451634355, diversity=1.0, silhouette=0.5868775248527527, mean_score=0.7211381566720627)

2025-10-29 12:44:08,738 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=31, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6683895159611517, diversity=1.0, silhouette=0.3333163261413574, mean_score=0.6672352807008363)

2025-10-29 12:46:14,020 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=16, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6683895159611517, diversity=1.0, silhouette=0.3333163261413574, mean_score=0.6672352807008363)

2025-10-29 12:48:17,567 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=52, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=100, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6683895159611517, diversity=1.0, silhouette=0.3333163261413574, mean_score=0.6672352807008363)

2025-10-29 12:50:21,378 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=49, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6683895159611517, diversity=1.0, silhouette=0.3333163261413574, mean_score=0.6672352807008363)

2025-10-29 12:52:26,271 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=34, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6683895159611517, diversity=1.0, silhouette=0.3333163261413574, mean_score=0.6672352807008363)

2025-10-29 12:54:30,178 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=22, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100, min_samples=5, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6361314419140327, diversity=1.0, silhouette=0.3318574428558349, mean_score=0.6559962949232893)

2025-10-29 12:56:45,461 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=19, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6361314419140327, diversity=1.0, silhouette=0.3318574428558349, mean_score=0.6559962949232893)

2025-10-29 12:58:48,635 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=37, n_neighbors=10, n_components=5, min_dist=0.0, min_cluster_size=150, min_samples=5, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6361314419140327, diversity=1.0, silhouette=0.3318574428558349, mean_score=0.6559962949232893)

2025-10-29 13:00:52,696 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=614, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.5297142568044332, diversity=1.0, silhouette=0.4088481068611145, mean_score=0.6461874545551826)

2025-10-29 13:03:23,966 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=583, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=10, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6228992485099181, diversity=1.0, silhouette=0.2801844775676727, mean_score=0.6343612420258636)

2025-10-29 13:05:50,498 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=586, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=10, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6228992485099181, diversity=1.0, silhouette=0.2801844775676727, mean_score=0.6343612420258636)

2025-10-29 13:08:17,371 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=592, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6158067226446935, diversity=1.0, silhouette=0.2864455580711365, mean_score=0.6340840935719433)

2025-10-29 13:10:47,739 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=589, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6158067226446935, diversity=1.0, silhouette=0.2864455580711365, mean_score=0.6340840935719433)

2025-10-29 13:13:17,738 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=617, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.5557613615808056, diversity=1.0, silhouette=0.3081148862838745, mean_score=0.6212920826215601)

2025-10-29 13:15:48,588 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=599, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=5, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.5615342442279618, diversity=1.0, silhouette=0.2960330843925476, mean_score=0.6191891095401698)

2025-10-29 13:18:20,006 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=613, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.1, embedding_model='all-distilroberta-v1', coherence=0.6606863946012334, diversity=1.0, silhouette=0.0946192368865013, mean_score=0.5851018771625782)

2025-10-29 13:20:51,308 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=616, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.6606863946012334, diversity=1.0, silhouette=0.0946192368865013, mean_score=0.5851018771625782)

2025-10-29 13:23:22,077 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=615, n_neighbors=20, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=5, cluster_eps=0.5, embedding_model='all-MiniLM-L6-v2', coherence=0.4624899008618601, diversity=1.0, silhouette=0.2509835064411163, mean_score=0.5711578024343255)

2025-10-29 13:25:54,141 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=58, n_neighbors=10, n_components=5, min_dist=0.1, min_cluster_size=50, min_samples=5, cluster_eps=0.5, embedding_model='all-distilroberta-v1', coherence=0.5122202334821168, diversity=1.0, silhouette=-0.3272409737110138, mean_score=0.3949930865903677)

2025-10-29 13:27:56,850 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_diversity/19' (gráfico salvo como HTML)

In [10]:
for i,row in enumerate(best_silhouette_row.itertuples()):
    print("Running BERTopic with parameters for best mean score:")
    print(row)
    model, topics, probs = run_bertopic_modeling(
        docs=sample_docs,
        n_neighbors=row.n_neighbors,
        n_components=row.n_components,
        min_dist=row.min_dist,
        min_cluster_size=row.min_cluster_size,
        min_samples=row.min_samples,
        cluster_eps=row.cluster_eps
    )
    dir = f"best_silhouette/{i}"
    if not os.path.exists(dir):
        os.makedirs(dir)
    save_results(model, dir)

Running BERTopic with parameters for best mean score:
Pandas(Index=575, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7460334473986139, diversity=0.99375, silhouette=0.850889265537262, mean_score=0.8635575709786253)

2025-10-29 13:30:27,255 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/0' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=572, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7460334473986139, diversity=0.99375, silhouette=0.850889265537262, mean_score=0.8635575709786253)

2025-10-29 13:32:58,402 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/1' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=287, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 13:35:21,121 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/2' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=305, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 13:37:44,349 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/3' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=284, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 13:40:06,507 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/4' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=302, n_neighbors=10, n_components=10, min_dist=0.5, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7421087837384722, diversity=0.98125, silhouette=0.8534843325614929, mean_score=0.8589477054333217)

2025-10-29 13:42:28,629 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/5' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=413, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7160172530564333, diversity=0.99375, silhouette=0.8218297958374023, mean_score=0.843865682964612)

2025-10-29 13:44:51,869 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/6' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=410, n_neighbors=20, n_components=5, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.7160172530564333, diversity=0.99375, silhouette=0.8218297958374023, mean_score=0.843865682964612)

2025-10-29 13:47:15,785 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/7' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=557, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6897430944738395, diversity=0.995, silhouette=0.8465607762336731, mean_score=0.8437679569025042)

2025-10-29 13:49:46,988 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/8' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=554, n_neighbors=20, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6897430944738395, diversity=0.995, silhouette=0.8465607762336731, mean_score=0.8437679569025042)

2025-10-29 13:52:17,676 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/9' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=266, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6719957762319849, diversity=0.9833333333333332, silhouette=0.8295090198516846, mean_score=0.8282793764723343)

2025-10-29 13:54:31,508 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/10' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=269, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=150, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6719957762319849, diversity=0.9833333333333332, silhouette=0.8295090198516846, mean_score=0.8282793764723343)

2025-10-29 13:56:45,795 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/11' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=251, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6669625134428905, diversity=0.99, silhouette=0.8221344351768494, mean_score=0.8263656495399133)

2025-10-29 13:59:00,041 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/12' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=248, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6669625134428905, diversity=0.99, silhouette=0.8221344351768494, mean_score=0.8263656495399133)

2025-10-29 14:01:13,444 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/13' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=230, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6387219664036587, diversity=0.9916666666666668, silhouette=0.8373963832855225, mean_score=0.8225950054519493)

2025-10-29 14:03:27,627 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/14' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=233, n_neighbors=10, n_components=10, min_dist=0.1, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6387219664036587, diversity=0.9916666666666668, silhouette=0.8373963832855225, mean_score=0.8225950054519493)

2025-10-29 14:05:41,097 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/15' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=197, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6348397920549981, diversity=0.9958333333333332, silhouette=0.8241742849349976, mean_score=0.8182824701077763)

2025-10-29 14:07:53,365 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/16' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=194, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=100, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6348397920549981, diversity=0.9958333333333332, silhouette=0.8241742849349976, mean_score=0.8182824701077763)

2025-10-29 14:10:06,268 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/17' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=179, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=50, min_samples=100, cluster_eps=0.5, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6171164119228348, diversity=0.9961538461538462, silhouette=0.8051778078079224, mean_score=0.8061493552948678)

2025-10-29 14:12:18,290 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/18' (gráfico salvo como HTML)
Running BERTopic with parameters for best mean score:
Pandas(Index=176, n_neighbors=10, n_components=10, min_dist=0.0, min_cluster_size=50, min_samples=100, cluster_eps=0.1, embedding_model='paraphrase-MiniLM-L6-v2', coherence=0.6171164119228348, diversity=0.9961538461538462, silhouette=0.8051778078079224, mean_score=0.8061493552948678)

2025-10-29 14:14:31,089 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

Modelo e resultados salvos no diretório 'best_silhouette/19' (gráfico salvo como HTML)