In [1]:
import pandas as pd

messages_path = "data/youtube_links.jsonl"
titles_path = "data/preprocessed_english_titles.csv"
infos_path = "data/youtube_titulos_saida.csv"
output_path = "data/youtube_telegram_cross.csv"

df_titles = pd.read_csv(titles_path)
df_infos = pd.read_csv(infos_path)
df_telegram = pd.read_json(messages_path, lines=True)

print(f"Preprocessed titles/descriptions: {len(df_titles)} entries")
display(df_titles.head())
print(f"Video metrics/metadata: {len(df_infos)} entries")
display(df_infos.head())
print(f"Telegram message occurrences: {len(df_telegram)} entries")
display(df_telegram.head())

Preprocessed titles/descriptions: 686626 entries

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text
0,0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Free bus travel for migrants scrapped. For 5 m...,en,free travel migrant scrap minute
1,1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",What is Spiritual Warfare? This charge I commi...,en,spiritual warfare charge commit unto thee timo...
2,2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...","80 Putins Have Layers In February 2024, Tucker...",en,putin layer february tucker carlson stand onio...
3,3,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,en,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...
4,4,AKU0RokegSo,Los Angeles rain: Studio City homes evacuated ...,An atmospheric river storm has caused mudslide...,Los Angeles rain: Studio City homes evacuated ...,en,angeles rain studio city home evacuate mudslid...

Video metrics/metadata: 1183816 entries

,video_id,title,description,channel_title,published_at,youtube_video_link,view_count,like_count,comment_count
0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Joe Marsh,2024-04-10T15:05:37Z,https://www.youtube.com/watch?v=jEKzQV5oajY,1057.0,152.0,32.0
1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",WWURD,2023-10-18T14:39:18Z,https://www.youtube.com/watch?v=xrGGce8cmx8,65.0,6.0,1.0
2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...",The Mosaic Ark,2024-02-22T07:30:05Z,https://www.youtube.com/watch?v=uaozGpSc4nc,330.0,8.0,6.0
3,TwACgO_oPq4,Anacondaz — Акуле плевать (Official Music Video),#Anacondaz #Акулеплевать #Безпаники\n\nLong St...,ANACONDAZ,2014-05-20T09:29:45Z,https://www.youtube.com/watch?v=TwACgO_oPq4,2321870.0,24565.0,561.0
4,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,https://www.youtube.com/watch?v=A59ftbhsQUE,806.0,136.0,18.0

Telegram message occurrences: 1920792 entries

,url,occurrences,id
0,http://www.youtube.com/watch?v=0BskDtKkX6Q,"[{'id': 12771, 'folder': 'channel_1205583420',...",0BskDtKkX6Q
1,http://www.youtube.com/watch?v=1L2V9Ml9Hi0,"[{'id': 88757, 'folder': 'channel_1181961026',...",1L2V9Ml9Hi0
2,http://www.youtube.com/watch?v=2EMyoELeAC0,"[{'id': 744, 'folder': 'channel_1639057388', '...",2EMyoELeAC0
3,http://www.youtube.com/watch?v=6PmrsXPrP0I,"[{'id': 274202, 'folder': 'channel_1153527121'...",6PmrsXPrP0I
4,http://www.youtube.com/watch?v=OKN8dFO_ZLA,"[{'id': 533712, 'folder': 'channel_1828686465'...",OKN8dFO_ZLA

### **1. Extracting the IDs from the links**

In [2]:
import re

def get_ID(url:str) -> str:
    #match = re.search(
    #        r"(?:v=|youtu\.be/|/v/|/embed/|/live/|/shorts/)([a-zA-Z0-9_-]{11})",
    #        url
    #    )
    match = re.search(
                r'(?:v=|\/|be\/|embed\/|shorts\/|watch\?v=)([a-zA-Z0-9_-]{11})',
                url
            )
    if match:
        return match.group(1)
    return None

In [5]:
import gzip
import json

objects = []
with open(messages_path, "rt") as f:
    for line in f:
        obj = json.loads(line)
        obj["id"] = get_ID(obj["url"])
        objects.append(obj)

In [7]:
with open(messages_path, "wt") as f:
    for obj in objects:
        f.write(json.dumps(obj) + "\n")

___
### **2. Combining the interesting columns**

#### *2.1 Combining with df_titles*

In [2]:
df_final = pd.DataFrame({
    "video_id": df_titles["video_id"],
    "text": df_titles["clean_text"]
})

#### *2.2 Combining with df_infos*

In [3]:
df_final = df_final.merge(
    df_infos[["video_id", "channel_title", "published_at", "view_count", "like_count", "comment_count"]],
    on="video_id",
    how="left"
)

#### *2.3 Combining with df_telegram*
But this has duplicate IDs, because different links can lead to the same ID, so that needs to be fixed first.

In [4]:
counts = df_telegram["id"].value_counts()
duplicates = counts[counts > 1]
print(duplicates)

id
_YIe_4LRQfI    306
hBMoPUAeLnY    284
c5wnRebTKKY    271
9-zF54xbFw0    180
8sEsfotldIY    145
              ...
pBDI7xv__Fo      2
1fsKvW8fcDw      2
p5attvG06uQ      2
KFppEuJRTO4      2
o821QX5LFpg      2
Name: count, Length: 235500, dtype: int64

In [5]:
video_id = "o821QX5LFpg"

# Filtra apenas as linhas com esse video_id
occurrences = df_telegram[df_telegram["id"] == video_id]

# Exibe todas as ocorrências
display(occurrences)
display(occurrences["occurrences"].tolist())

,url,occurrences,id
142450,https://youtu.be/o821QX5LFpg?si=DDetjzACmDqnrMra,"[{'id': 11707, 'folder': 'channel_1577438065',...",o821QX5LFpg
872570,https://youtu.be/o821QX5LFpg?si=bT00jO37-EOlT7ba,"[{'id': 10923, 'folder': 'channel_1385694192',...",o821QX5LFpg

[[{'id': 11707, 'folder': 'channel_1577438065', 'date': '2023-11-30'}],
 [{'id': 10923, 'folder': 'channel_1385694192', 'date': '2023-12-02'}]]

In [6]:
df_telegram = df_telegram.rename(columns={"id": "video_id"})

#Como um id pode ter mais de um link, agrupa essas ocorrências
df_telegram_unique = df_telegram.groupby("video_id")["occurrences"].apply(list).reset_index()

df_telegram_unique = (
    df_telegram.groupby("video_id")["occurrences"]
    .apply(lambda x: [item for sublist in x for item in sublist])
    .reset_index()
)

In [7]:
video_id = "o821QX5LFpg"

# Filtra apenas as linhas com esse video_id
occurrences = df_telegram_unique[df_telegram_unique["video_id"] == video_id]

# Exibe todas as ocorrências
display(occurrences)
display(occurrences["occurrences"].tolist())

            video_id                                        occurrences
1139383  o821QX5LFpg  [{'id': 11707, 'folder': 'channel_1577438065',...

[[{'id': 11707, 'folder': 'channel_1577438065', 'date': '2023-11-30'},
  {'id': 10923, 'folder': 'channel_1385694192', 'date': '2023-12-02'}]]

In [8]:
df_final = df_final.merge(
    df_telegram_unique,
    on="video_id",
    how="left"
)

In [9]:
display(df_final.head())

,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences
0,jEKzQV5oajY,free travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ..."
1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',..."
2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',..."
3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'..."
4,AKU0RokegSo,angeles rain studio city home evacuate mudslid...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'..."

In [10]:
df_final.to_csv(output_path)

#### *2.3 Combining with toxics*

In [3]:
import pandas as pd

infos_path = "data/youtube_telegram_cross.csv"
toxics_path = "data/videos_with_toxics.csv"

df_final = pd.read_csv(infos_path)
df_toxics = pd.read_csv(toxics_path)

print(f"Cross Telegram Youtube: {len(df_final)} entries")
display(df_final.head())
print(f"Toxics of videos: {len(df_toxics)} entries")
display(df_toxics.head())

/tmp/ipykernel_1674323/479903545.py:7: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_toxics = pd.read_csv(toxics_path)

Cross Telegram Youtube: 686626 entries

,Unnamed: 0,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences
0,0,jEKzQV5oajY,free travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ..."
1,1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',..."
2,2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',..."
3,3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'..."
4,4,AKU0RokegSo,angeles rain studio city home evacuate mudslid...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'..."

Toxics of videos: 702930 entries

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack
0,0,jEKzQV5oajY,Free bus travel for migrants scrapped. For 5 m...,NaN,Free bus travel for migrants scrapped. For 5 m...,en,travel migrant scrap minute,0.000659,0.000117,0.000183,0.000114,0.000178,0.000138
1,1,xrGGce8cmx8,What is Spiritual Warfare?,"This charge I commit unto thee, son Timothy, a...",What is Spiritual Warfare? This charge I commi...,en,spiritual warfare charge commit unto thee timo...,0.295000,0.001137,0.003694,0.012858,0.003023,0.006275
2,2,uaozGpSc4nc,80 Putins Have Layers,"In February 2024, Tucker Carlson stood in fron...","80 Putins Have Layers In February 2024, Tucker...",en,putin layer february tucker carlson stand onio...,0.001735,0.000102,0.000245,0.000142,0.000204,0.000156
3,3,A59ftbhsQUE,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,#pleiadians #5dimension #ashtar\n#pleiadians #...,𝐆𝐀𝐋𝐀𝐂𝐓𝐈𝐂 𝐀𝐋𝐋𝐈𝐀𝐍𝐂𝐄 𝐌𝐄𝐒𝐒𝐀𝐆𝐄|𝐁𝐈𝐆 𝐍𝐄𝐖𝐒!~𝐑𝐄𝐌𝐀𝐈𝐍 𝐀𝐋𝐄...,en,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,0.002710,0.000104,0.000254,0.000185,0.000239,0.000192
4,4,AKU0RokegSo,Los Angeles rain: Studio City homes evacuated ...,An atmospheric river storm has caused mudslide...,Los Angeles rain: Studio City homes evacuated ...,en,angeles rain studio city evacuate mudslide atm...,0.001515,0.000100,0.000217,0.000126,0.000203,0.000143

In [ ]:
cols = ["video_id", "toxicity", "severe_toxicity", "obscene", "threat", "insult", "identity_attack"]
df_final = df_final.merge(
    df_toxics[cols],
    on="video_id",
    how="left"
)

Merged dataset: 715920 entries

,Unnamed: 0,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,obscene,threat,insult,identity_attack
0,0,jEKzQV5oajY,free travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ...",0.000659,0.000117,0.000183,0.000114,0.000178,0.000138
1,1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',...",0.295000,0.001137,0.003694,0.012858,0.003023,0.006275
2,2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',...",0.001735,0.000102,0.000245,0.000142,0.000204,0.000156
3,3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'...",0.002710,0.000104,0.000254,0.000185,0.000239,0.000192
4,4,AKU0RokegSo,angeles rain studio city home evacuate mudslid...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'...",0.001515,0.000100,0.000217,0.000126,0.000203,0.000143

In [ ]:
df_final = df_final.drop_duplicates(subset='video_id', keep='first')
print(f"Merged dataset: {len(df_final)} entries")
display(df_final.head())

Merged dataset: 686626 entries

In [10]:
df_final.to_csv(infos_path)

___
### **3. Creating the sample with topics**

In [3]:
import pandas as pd 

topics_path = "data/sample_df_with_topics.csv"
infos_path = "data/youtube_telegram_cross.csv"

df_final = pd.read_csv(infos_path)
df_topics = pd.read_csv(topics_path)

print(f"Cross Telegram Youtube: {len(df_final)} entries")
display(df_final.head())
print(f"Topics of videos: {len(df_topics)} entries")
display(df_topics.head())

Cross Telegram Youtube: 686626 entries

,Unnamed: 0.1,Unnamed: 0,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,obscene,threat,insult,identity_attack
0,0,0,jEKzQV5oajY,free travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ...",0.000659,0.000117,0.000183,0.000114,0.000178,0.000138
1,1,1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',...",0.295000,0.001137,0.003694,0.012858,0.003023,0.006275
2,2,2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',...",0.001735,0.000102,0.000245,0.000142,0.000204,0.000156
3,3,3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'...",0.002710,0.000104,0.000254,0.000185,0.000239,0.000192
4,4,4,AKU0RokegSo,angeles rain studio city home evacuate mudslid...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'...",0.001515,0.000100,0.000217,0.000126,0.000203,0.000143

Topics of videos: 90972 entries

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text,topic
0,474588,BRhODqge9dY,Guns N' Roses - November Rain (Lyrics),Guns N' Roses - Use Your Illusion I[2 LP] - Do...,Guns N' Roses - November Rain (Lyrics) Guns N...,en,rose november rain lyric rose illusion double ...,1.0
1,410902,qmjXoaGxRQw,Traditional craftsmanship of the Mongol Ger an...,UNESCO: Representative List of the Intangible ...,Traditional craftsmanship of the Mongol Ger an...,en,traditional craftsmanship mongol associate cus...,-1.0
2,408471,zQRYk7stYIw,Angel Baby,A screen representation of Rosie and the Origi...,Angel Baby A screen representation of Rosie an...,en,angel baby screen representation rosie origina...,-1.0
3,541647,mhhMPI86jhQ,Climate activists block Dodge RAM TRX and face...,I hope you guys realize its fake :) pls dont d...,Climate activists block Dodge RAM TRX and face...,en,climate activist block dodge face consequence ...,-1.0
4,613477,IcD_22IC5l0,Ricky Gervais // Minorities // #shorts,NaN,Ricky Gervais // Minorities // #shorts,en,ricky gervais minority,25.0

In [4]:
df_topics = df_topics.drop_duplicates(subset='video_id', keep='first')
print(f"Topics after removing duplicates: {len(df_topics)} entries")

Topics after removing duplicates: 67362 entries

In [11]:
df_topics[df_topics["topic"].isna()]

,Unnamed: 0,video_id,title,description,title_description,lang,clean_text,topic
28536,208989,3ZjtWo8XDNQ,Bidens Invite Nurses To Do Musical Number At W...,A group of nurses performed a,NaN,NaN,NaN,NaN
28537,Christmas song at the White House.,Bidens Invite Nurses To Do Musical Number At W...,NaN,NaN,NaN,NaN,NaN,NaN
28538,Christmas song at the White House.,en,bidens invite nurse musical number white house...,-1,NaN,NaN,NaN,NaN
41925,102614,aX_RHGSwfRE,Paula Abdul,NaN,NaN,NaN,NaN,NaN
65536,- Cold Hearted,Subscribe to our channel for all your favourit...,Paula Abdul\r - Cold Hearted Subscribe to our ...,en,paula abdul cold hearted favourite artist lyri...,1,NaN,NaN

In [ ]:
df_final = df_final.loc[:, ~df_final.columns.str.contains('^Unnamed')]
display(df_final.head())

,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,obscene,threat,insult,identity_attack
0,jEKzQV5oajY,free travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ...",0.000659,0.000117,0.000183,0.000114,0.000178,0.000138
1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',...",0.295000,0.001137,0.003694,0.012858,0.003023,0.006275
2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',...",0.001735,0.000102,0.000245,0.000142,0.000204,0.000156
3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'...",0.002710,0.000104,0.000254,0.000185,0.000239,0.000192
4,AKU0RokegSo,angeles rain studio city home evacuate mudslid...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'...",0.001515,0.000100,0.000217,0.000126,0.000203,0.000143

In [7]:
df_final.to_csv(infos_path, index=False)

In [8]:
df = df_final.merge(df_topics[['video_id', 'topic']], on='video_id', how='left')
display(df.head())

,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,topic
0,jEKzQV5oajY,free travel migrant scrap minute,Joe Marsh,2024-04-10T15:05:37Z,1057.0,152.0,32.0,"[{'id': 1416, 'folder': 'channel_1556142220', ...",0.000659,0.000117,0.000183,0.000114,0.000178,0.000138,NaN
1,xrGGce8cmx8,spiritual warfare charge commit unto thee timo...,WWURD,2023-10-18T14:39:18Z,65.0,6.0,1.0,"[{'id': 60799, 'folder': 'channel_1466271872',...",0.295000,0.001137,0.003694,0.012858,0.003023,0.006275,NaN
2,uaozGpSc4nc,putin layer february tucker carlson stand onio...,The Mosaic Ark,2024-02-22T07:30:05Z,330.0,8.0,6.0,"[{'id': 40486, 'folder': 'channel_1235978663',...",0.001735,0.000102,0.000245,0.000142,0.000204,0.000156,NaN
3,A59ftbhsQUE,GALACTIC ALLIANCE MESSAGE NEWS REMAIN ALERT PR...,GALACTIC ALLIANCE,2024-10-27T04:30:04Z,806.0,136.0,18.0,"[{'id': 449843, 'folder': 'channel_1571505334'...",0.002710,0.000104,0.000254,0.000185,0.000239,0.000192,NaN
4,AKU0RokegSo,angeles rain studio city home evacuate mudslid...,FOX 11 Los Angeles,2024-02-06T01:45:29Z,60863.0,406.0,152.0,"[{'id': 104116, 'folder': 'channel_1438734111'...",0.001515,0.000100,0.000217,0.000126,0.000203,0.000143,NaN

In [10]:
df_sem_nan = df.dropna(subset=["topic"])
display(df_sem_nan.head())
print(f"Dataset after dropping NaN topics: {len(df_sem_nan)} entries")

,video_id,text,channel_title,published_at,view_count,like_count,comment_count,occurrences,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,topic
6,QKXr7N9c6Yo,roman islamic antichrist sonia azam explore bi...,Armageddon News,2021-10-11T16:36:04Z,2249.0,107.0,75.0,"[{'id': 28786, 'folder': 'channel_2165208912',...",0.003288,0.000109,0.000247,0.000162,0.000228,0.000284,0.0
7,qRFdVxvlXRY,kamala interview prove weak hope prove point w...,Real America's Voice,2024-10-08T14:57:04Z,498.0,89.0,10.0,"[{'id': 33565, 'folder': 'channel_1937328148',...",0.000926,0.000104,0.000178,0.000124,0.000195,0.000136,2.0
36,Y8KzbOkN_TM,money ttaakaa syllabus baire epbong welcome ep...,Your Bong Guy,2024-11-07T12:23:25Z,1198216.0,103644.0,5457.0,"[{'id': 3555926, 'folder': 'channel_1279841660...",0.005160,0.000092,0.000415,0.000128,0.000365,0.000166,-1.0
52,B5yS8olxa80,save israel jeremy gimpel live update frontlin...,thelandofisrael,2023-11-28T16:48:23Z,11835.0,1668.0,212.0,"[{'id': 37539, 'folder': 'channel_1592308283',...",0.002251,0.000098,0.000225,0.000128,0.000196,0.000200,4.0
54,JnvOJN5yF8s,kingdom planet official trailer cinemas yang b...,20th Century Studios Indonesia,2024-02-12T01:24:59Z,211122.0,1928.0,374.0,"[{'id': 422797, 'folder': 'channel_1905119305'...",0.001937,0.000101,0.000238,0.000136,0.000227,0.000176,-1.0

Dataset after dropping NaN topics: 67357 entries

In [13]:
df_sem_nan.to_csv("data/sample_yt_te_cross_with_topics.csv", index=False)

In [15]:
df_sem_nan["topic"].value_counts()

topic
-1.0     19149
 0.0     10227
 1.0      8664
 2.0      4057
 3.0      3432
         ...
 56.0      120
 57.0      117
 58.0      112
 59.0      108
 60.0      106
Name: count, Length: 62, dtype: int64